name: SMBcorr
channels:
  - conda-forge
dependencies:
  - python>=3.6
  - notebook
  - numpy
  - scipy
  - pyproj
  - python-dateutil
  - netCDF4
  - scikit-learn
  - pip
  - pip:
     - git+https://github.com/SmithB/pointCollection.git
