name: SMBcorr
channels:
  - conda-forge
dependencies:
  - gdal
  - lxml
  - notebook
  - numpy
  - netCDF4
  - pip
  - pyproj
  - python>=3.6
  - python-dateutil
  - scikit-learn
  - scipy>=1.10.1
  - pip:
     - git+https://github.com/SmithB/pointCollection.git
